import type { Metadata } from "next";
import "./globals.css";
import Providers from "@/app/Providers";
import { newTheme } from "@/app/theme";
import AppHeader from "@/app/AppHeader";
import AppFooter from "@/app/AppFooter";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="ja">
      <body>
        <Providers themes={[newTheme]}>
          <AppHeader />
          <main>{children}</main>
          <AppFooter />
        </Providers>
      </body>
    </html>
  );
};

export default RootLayout;
